# Práctica Clase 3

## Numpy

In [ ]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

A partir de una lista podemos crear un arreglo de numpy

In [ ]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

In [ ]:
#Slicing, sirve en ambos
print(lista[:3])
print(arreglo[:3])

Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [ ]:
arreglo1 = np.arange(8)
print(arreglo1)

Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [ ]:
#No se puede con listas
lista + 1

In [ ]:
#Si se puede con Np
arreglo = arreglo - 1

In [ ]:
print(arreglo)

2. Elevar al cuadrado todos los elementos

In [ ]:
lista**2

In [ ]:
arreglo**2

3. Sumar todos los elementos

In [ ]:
print(arreglo.sum())
print(sum(lista))

In [ ]:
n = 0
for e in lista:
    n = n + e
print(n)

In [ ]:
arreglo1.shape

In [ ]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

In [ ]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

In [ ]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

In [ ]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


(n,) es un arreglo unidimensional de n elementos
(n,m) es una matriz de n filas y m columnas

In [ ]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

In [ ]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

In [ ]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape

In [ ]:
a3 = a1 * a2
a3.shape

In [ ]:
a3

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [ ]:
arreglo = np.arange(10)
print(arreglo)
arreglo = np.linspace(0,10,100)
print(arreglo)

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [20]:
arreglo = np.arange(10,101)
print(arreglo)
mask = arreglo % 3 == 0
print(arreglo[mask])

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96 99]


**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [22]:
arreglo = np.zeros((5,10))
print(arreglo)
arreglo[(1,3),:] = 1
arreglo[:,(2,7)] = 2
print(arreglo)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]]


**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [21]:
a = np.random.random((4,2,3)) * 100
a

array([[[43.38516797,  2.7660291 , 62.14262605],
        [57.15258654,  7.73626289, 21.71999119]],

       [[33.23524504, 94.38468915,  2.21938814],
        [ 0.98008524, 66.15144718, 63.49859615]],

       [[58.69671451,  7.57875895, 28.81355694],
        [40.76700131, 28.65031874, 66.81237266]],

       [[14.17205678, 91.17479759, 71.06925926],
        [58.20732746, 81.19202587,  6.58420268]]])

In [ ]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)

In [ ]:
a.sum()

In [ ]:
a.std()

In [ ]:
a.sort(axis=1)

In [ ]:
a.sort(axis=0)
a

In [ ]:
a[1:3,0:3]

In [ ]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [ ]:
a = np.array([l])

In [ ]:
a.shape

In [ ]:
a.reshape(24)

In [ ]:
a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 

In [ ]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

In [ ]:
c = a * b 
print(c) 

In [ ]:
d = b * a 
print(d)